"""Deterministic KickAssembler export for 19656 level projects."""
from pathlib import Path

from engine_data import METATILE_NAMES, METATILES_PER_ROW
from project import (
    ProjectValidationError,
    export_readiness_errors,
    iter_turrets,
    turret_world_col,
    turret_world_row,
    validate_project,
)


def _byte_line(values, comment=None):
    body = ",".join(f"{value:3d}" for value in values)
    line = f"    .byte {body}"
    if comment:
        line += f"   // {comment}"
    return line


def render_stage_config(project):
    errors = validate_project(project)
    if errors:
        raise ProjectValidationError("\n".join(errors))
    p = project.palette
    return "\n".join([
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Project: {project.name}",
        "//",
        "// CONSTANTS-ONLY level-config include. Emits no bytes, no memory segment,",
        "// no program-counter change. It is imported very early (immediately after",
        "// variables.asm) so every level-owned constant exists before the engine",
        "// constants/code that consume them.",
        "//",
        "// Ownership: these values belong to the level project, NOT to the engine.",
        "// The engine derives STAGE_LOGICAL_ROWS = STAGE_METATILE_ROWS * METATILE_H.",
        "// Runtime palette mapping:",
        "//   TERRAIN_BACKGROUND_COLOUR -> $D021",
        "//   TERRAIN_MC_COLOUR_1       -> $D022   (multicolour bit-pair 01)",
        "//   TERRAIN_MC_COLOUR_2       -> $D023   (multicolour bit-pair 10)",
        "//   TERRAIN_CHARACTER_COLOUR  -> colour RAM low 3 bits (bit-pair 11)",
        "//   colour RAM bit 3 set     -> per-cell multicolour terrain",
        "// ============================================================================",
        f".const STAGE_METATILE_ROWS     = {project.height}",
        f".const SCROLL_FRAME_DIVIDER    = {project.scroll_frame_divider}",
        f".const TERRAIN_BACKGROUND_COLOUR = {p['background']}",
        f".const TERRAIN_MC_COLOUR_1     = {p['multicolour1']}",
        f".const TERRAIN_MC_COLOUR_2     = {p['multicolour2']}",
        f".const TERRAIN_CHARACTER_COLOUR = {p['character']}",
        ".const TERRAIN_COLOUR_RAM      = 8 | TERRAIN_CHARACTER_COLOUR",
        "",
    ])


def render_stage_asm(project, metatiles):
    errors = validate_project(project)
    if errors:
        raise ProjectValidationError("\n".join(errors))
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Project: {project.name}",
        f"// {project.height} metatile rows x {METATILES_PER_ROW} columns.",
        "// Terrain colour is level-global; there is intentionally no per-cell colour table.",
        "// ============================================================================",
        "",
        "metatileDefs:",
    ]
    for tile_id, tile in enumerate(metatiles):
        lines.append(_byte_line(tile, f"M{tile_id} {METATILE_NAMES[tile_id]}"))
    lines.extend(["METATILE_DEFS_END:", "", "stageMetatileRows:"])
    for row_index, row in enumerate(project.metatile_rows):
        lines.append(_byte_line(row, f"row {row_index}"))
    lines.extend([
        "STAGE_METATILE_ROWS_END:",
        "// Size/memory guards remain engine-owned immediately after this include.",
        "",
    ])
    return "\n".join(lines)


def render_stage_turrets(project):
    """Authored turret PLACEMENT only. Behaviour (AI, cadence, HP, rendering,
    activation, collision) stays entirely engine-owned in background_turrets.asm.

    Emits the engine's existing placement representation directly - no new
    structure imposed:
        .const TURRET_COUNT
        .var   turretCols   (world CHARACTER columns, one per turret)
        .var   turretRows   (world CHARACTER / logical rows, full stage height,
                             16-bit-safe: values well above 255 are fine)
    Deterministic: turrets are emitted in (metatileRow, metatileCol) order.
    """
    errors = export_readiness_errors(project)
    if errors:
        raise ProjectValidationError("\n".join(errors))
    turrets = iter_turrets(project)
    cols = [turret_world_col(t["metatileCol"]) for t in turrets]
    rows = [turret_world_row(t["metatileRow"]) for t in turrets]
    return "\n".join([
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Project: {project.name}",
        "//",
        "// Authored turret PLACEMENT layer. Constants + assembler lists only: no",
        "// bytes, no segment, no program-counter change. Imported early (right after",
        "// stage_config.asm) so TURRET_COUNT resolves before any consumer.",
        "//",
        "// PLACEMENT is editor-owned; BEHAVIOUR stays engine-owned",
        "// (src/background_turrets.asm). turretRows are world CHARACTER rows for the",
        "// FULL stage height - values above 255 are supported (16-bit world rows).",
        "//   world row = metatileRow * 4 + 1     world col = metatileCol * 4 + 1",
        "// ============================================================================",
        f".const TURRET_COUNT = {len(turrets)}",
        f".var turretCols = List().add({', '.join(str(c) for c in cols)})",
        f".var turretRows = List().add({', '.join(str(r) for r in rows)})",
        "",
    ])


def export_project(project, metatiles, output_dir):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "stage_config.asm"
    stage_path = output_dir / "stage_test.asm"
    turrets_path = output_dir / "stage_turrets.asm"
    config_path.write_text(render_stage_config(project), encoding="utf-8")
    stage_path.write_text(render_stage_asm(project, metatiles), encoding="utf-8")
    turrets_path.write_text(render_stage_turrets(project), encoding="utf-8")
    return config_path, stage_path, turrets_path
