"""Deterministic KickAssembler export for 19656 level packages.

Each level exports a directory of five includes:
    stage_config.asm    constants: height, scroll divider, terrain palette
    stage_charset.asm    the level's own terrain glyph bitmaps + TERRAIN_GLYPH_COUNT
    stage_test.asm       metatileDefs (from the level tileset) + stageMetatileRows
    stage_turrets.asm    TURRET_TOTAL + turretCols/turretRows (desc by world row)
    stage_waves.asm      WAVE_TRIGGER_COUNT + resolved authored wave-trigger lists

Gameplay imports one level's directory (level1/); other levels coexist on disk
unreferenced. Re-running the exporter is byte-identical.
"""
from pathlib import Path

from engine_data import (
    METATILE_NAMES,
    METATILES_PER_ROW,
    TERRAIN_GLYPH_BASE,
    TURRET_POOL,
)
from project import (
    ProjectValidationError,
    composition_size,
    iter_turrets,
    turret_world_col,
    turret_world_row,
    validate_project,
)

CONFIG_NAME = "stage_config.asm"
CHARSET_NAME = "stage_charset.asm"
STAGE_NAME = "stage_test.asm"
TURRETS_NAME = "stage_turrets.asm"
WAVES_NAME = "stage_waves.asm"


def _byte_line(values, comment=None):
    body = ",".join(f"{value:3d}" for value in values)
    line = f"    .byte {body}"
    if comment:
        line += f"   // {comment}"
    return line


def _require_valid(project):
    errors = validate_project(project)
    if errors:
        raise ProjectValidationError("\n".join(errors))


def _sorted_turrets_desc(project):
    """Turrets as (world_row, world_col), sorted DESCENDING by world row - the
    order gameplay's downward-scrolling SCROLL_ROW crosses them, which the engine
    streaming cursor walks."""
    entries = [
        (turret_world_row(t["metatileRow"]), turret_world_col(t["metatileCol"]))
        for t in iter_turrets(project)
    ]
    entries.sort(key=lambda rc: (-rc[0], rc[1]))
    return entries


# --- individual includes -------------------------------------------------------

def render_stage_config(project):
    _require_valid(project)
    p = project.palette
    glyph_count = len(project.tileset["glyphs"]) if project.tileset else None
    metatile_count = len(project.tileset["metatileDefs"]) if project.tileset else None
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// CONSTANTS-ONLY level-config include. Emits no bytes, no memory segment,",
        "// no program-counter change. Imported very early so every level-owned",
        "// constant exists before the engine constants/code that consume them.",
        "//",
        "// Ownership: these values belong to the level package, NOT to the engine.",
        "// The engine derives STAGE_LOGICAL_ROWS = STAGE_METATILE_ROWS * METATILE_H",
        "// and METATILE_DEF_COUNT = STAGE_METATILE_COUNT (the level's metatile-def",
        "// table is variable length: STAGE_METATILE_COUNT * 16 bytes, 1..64).",
        "//   TERRAIN_BACKGROUND_COLOUR -> $D021",
        "//   TERRAIN_MC_COLOUR_1       -> $D022   (multicolour bit-pair 01)",
        "//   TERRAIN_MC_COLOUR_2       -> $D023   (multicolour bit-pair 10)",
        "//   TERRAIN_CHARACTER_COLOUR  -> colour RAM low 3 bits (bit-pair 11)",
        "// TERRAIN_GLYPH_COUNT is level-owned too (the tileset lives in",
        "// stage_charset.asm); it is declared here so the engine's early glyph-",
        "// namespace guards resolve before the byte block is imported.",
        "// ============================================================================",
        f".const STAGE_METATILE_ROWS     = {project.height}",
        f".const SCROLL_FRAME_DIVIDER    = {project.scroll_frame_divider}",
        *([f".const STAGE_METATILE_COUNT   = {metatile_count}"] if metatile_count is not None else []),
        f".const TERRAIN_BACKGROUND_COLOUR = {p['background']}",
        f".const TERRAIN_MC_COLOUR_1     = {p['multicolour1']}",
        f".const TERRAIN_MC_COLOUR_2     = {p['multicolour2']}",
        f".const TERRAIN_CHARACTER_COLOUR = {p['character']}",
        ".const TERRAIN_COLOUR_RAM      = 8 | TERRAIN_CHARACTER_COLOUR",
    ]
    if glyph_count is not None:
        lines.append(f".const TERRAIN_GLYPH_COUNT     = {glyph_count}")
    lines.append("")
    return "\n".join(lines)


def render_stage_charset(project):
    """The level's own terrain glyph bitmaps. This is the swappable 512-byte
    tileset unit: char codes TERRAIN_GLYPH_BASE .. TERRAIN_GLYPH_BASE+COUNT-1
    ($3D00..). A future multiload transition replaces exactly this block."""
    _require_valid(project)
    if not project.tileset:
        raise ProjectValidationError("Level has no tileset; cannot render stage_charset.asm.")
    glyphs = project.tileset["glyphs"]
    count = len(glyphs)
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// LEVEL-OWNED terrain glyph bitmaps - the swappable tileset unit. Codes",
        "// 160..223 are the permanent terrain glyph namespace ($3D00-$3EFF, 64",
        f"// slots); this level authors the first {count}. initBackground copies",
        "// TERRAIN_GLYPH_COUNT glyphs (declared in stage_config.asm) to $3D00.",
        "// A future multiload transition replaces exactly this byte block.",
        "// ============================================================================",
        "terrainGlyphs:",
    ]
    for i, glyph in enumerate(glyphs):
        lines.append(_byte_line([b & 0xFF for b in glyph], f"code {TERRAIN_GLYPH_BASE + i}"))
    lines.extend([
        "terrainGlyphsEnd:",
        ".if (terrainGlyphsEnd - terrainGlyphs != TERRAIN_GLYPH_COUNT * 8) {",
        '    .error "terrainGlyphs data size does not match TERRAIN_GLYPH_COUNT * 8"',
        "}",
        "",
    ])
    return "\n".join(lines)


def render_stage_asm(project, metatiles=None):
    _require_valid(project)
    if project.tileset:
        defs = project.tileset["metatileDefs"]
    elif metatiles is not None:
        defs = metatiles
    else:
        raise ProjectValidationError("render_stage_asm needs a tileset or an explicit metatiles list.")
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        f"// {project.height} metatile rows x {METATILES_PER_ROW} columns.",
        "// Terrain colour is level-global; there is intentionally no per-cell colour table.",
        "// ============================================================================",
        "",
        "metatileDefs:",
    ]
    for tile_id, tile in enumerate(defs):
        name = METATILE_NAMES[tile_id] if tile_id < len(METATILE_NAMES) else f"M{tile_id}"
        lines.append(_byte_line(tile, f"M{tile_id} {name}"))
    lines.extend(["METATILE_DEFS_END:", "", "stageMetatileRows:"])
    for row_index, row in enumerate(project.metatile_rows):
        lines.append(_byte_line(row, f"row {row_index}"))
    lines.extend([
        "STAGE_METATILE_ROWS_END:",
        "// Size/memory guards remain engine-owned immediately after this include.",
        "",
    ])
    return "\n".join(lines)


def render_stage_turrets(project):
    """Authored turret PLACEMENT only. Behaviour stays engine-owned.

        .const TURRET_TOTAL          authored count (0..255)
        .var   turretCols            world CHARACTER columns
        .var   turretRows            world CHARACTER / logical rows (16-bit safe)

    Sorted DESCENDING by world row (streaming-cursor order). Authoring order is
    irrelevant to the output."""
    _require_valid(project)
    entries = _sorted_turrets_desc(project)
    rows = [r for r, _ in entries]
    cols = [c for _, c in entries]
    add_cols = f".add({', '.join(str(c) for c in cols)})" if cols else ""
    add_rows = f".add({', '.join(str(r) for r in rows)})" if rows else ""
    return "\n".join([
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// Authored turret PLACEMENT layer. Constants + assembler lists only.",
        "// PLACEMENT is editor-owned; BEHAVIOUR stays engine-owned",
        "// (src/background_turrets.asm). The engine streams these through a fixed",
        f"// pool of {TURRET_POOL} live glyph slots as SCROLL_ROW crosses them.",
        "//   world row = metatileRow * 4 + 1     world col = metatileCol * 4 + 1",
        "//   values above 255 are supported (16-bit world rows).",
        "// ============================================================================",
        f".const TURRET_TOTAL = {len(entries)}",
        f".var turretCols = List(){add_cols}",
        f".var turretRows = List(){add_rows}",
        "",
    ])


def _resolve_triggers(project, engine_data):
    """Resolve each authored trigger to the flat lists the engine consumes.
    Returns rows (desc), attack_ids, counts, sprite_seeds, intervals."""
    intervals = list(engine_data.attack_intervals) if engine_data else []
    sprite_start = list(engine_data.attack_sprite_start) if engine_data else []

    resolved = []
    for wt in project.canonical_wave_triggers():
        wd = project.wave_definition(wt["waveDef"])
        attack_id = int(wd["attackId"])
        comp = wd.get("composition", [{"enemyType": 0, "count": 5}])
        size = composition_size(wd) or 5
        window_start = sprite_start[attack_id] if attack_id < len(sprite_start) else 0
        max_count = min(8, 32 - window_start)
        count = max(1, min(size, max_count))
        enemy_type = int(comp[0].get("enemyType", 0))
        sprite_seed = enemy_type * 8
        interval = wd.get("spawnInterval", None)
        if interval in (None, ""):
            interval = intervals[attack_id] if attack_id < len(intervals) else 16
        resolved.append((int(wt["worldRow"]), attack_id, count, sprite_seed, int(interval)))

    resolved.sort(key=lambda r: -r[0])
    rows = [r[0] for r in resolved]
    return (
        rows,
        [r[1] for r in resolved],
        [r[2] for r in resolved],
        [r[3] for r in resolved],
        [r[4] for r in resolved],
    )


def render_stage_waves(project, engine_data=None):
    """Authored enemy-wave TIMING. A trigger fires the instant its authored
    terrain row enters the top edge of the aperture (SCROLL_ROW == worldRow).
    When WAVE_TRIGGER_COUNT == 0 the engine keeps its autonomous CIA-random
    wave sequencing; when > 0, authored triggers become the encounter timing
    source and autonomous selection is bypassed for this stage."""
    _require_valid(project)
    rows, attack_ids, counts, sprites, intervals = _resolve_triggers(project, engine_data)

    def _list(name, values):
        add = f".add({', '.join(str(v) for v in values)})" if values else ""
        return f".var {name} = List(){add}"

    row_lo = [r & 0xFF for r in rows]
    row_hi = [(r >> 8) & 0xFF for r in rows]
    return "\n".join([
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// Authored wave TRIGGERS. Constants + assembler lists only. Each trigger",
        "// fires when its authored world/logical row reaches the top edge of the",
        "// terrain aperture (SCROLL_ROW == worldRow). Rows are sorted DESCENDING -",
        "// the order the downward-scrolling SCROLL_ROW crosses them. worldRow is a",
        "// world position, NOT a frame count: SCROLL_FRAME_DIVIDER does not move it.",
        "//",
        "// Resolved from wave definitions:",
        "//   waveTriggerAttackId  - curated attack catalogue id (formation+pattern)",
        "//   waveTriggerCount     - composition size (authoritative wave size)",
        "//   waveTriggerSprite    - WAVE_SPRITE_INDEX seed = enemyType * 8",
        "//   waveTriggerInterval  - frames between members (def override or attack default)",
        "// ============================================================================",
        f".const WAVE_TRIGGER_COUNT = {len(rows)}",
        _list("waveTriggerRowLo", row_lo),
        _list("waveTriggerRowHi", row_hi),
        _list("waveTriggerAttackId", attack_ids),
        _list("waveTriggerCount", counts),
        _list("waveTriggerSprite", sprites),
        _list("waveTriggerInterval", intervals),
        "",
    ])


# --- level export ------------------------------------------------------------

def export_level(project, output_dir, *, engine_data=None, metatiles=None):
    """Write all five generated includes for one level package. Returns the five
    paths in canonical order (config, charset, stage, turrets, waves)."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / CONFIG_NAME
    charset_path = output_dir / CHARSET_NAME
    stage_path = output_dir / STAGE_NAME
    turrets_path = output_dir / TURRETS_NAME
    waves_path = output_dir / WAVES_NAME
    config_path.write_text(render_stage_config(project), encoding="utf-8")
    charset_path.write_text(render_stage_charset(project), encoding="utf-8")
    stage_path.write_text(render_stage_asm(project, metatiles), encoding="utf-8")
    turrets_path.write_text(render_stage_turrets(project), encoding="utf-8")
    waves_path.write_text(render_stage_waves(project, engine_data), encoding="utf-8")
    return config_path, charset_path, stage_path, turrets_path, waves_path


def export_project(project, metatiles, output_dir):
    """Back-compat 3-file export (config, stage, turrets) into a single dir.
    Prefer export_level for the full level package."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / CONFIG_NAME
    stage_path = output_dir / STAGE_NAME
    turrets_path = output_dir / TURRETS_NAME
    config_path.write_text(render_stage_config(project), encoding="utf-8")
    stage_path.write_text(render_stage_asm(project, metatiles), encoding="utf-8")
    turrets_path.write_text(render_stage_turrets(project), encoding="utf-8")
    return config_path, stage_path, turrets_path
