#!/usr/bin/env python3
"""Emit a deterministic stage_test.asm fixture with N metatile rows.

Keeps the real 16 metatileDefs (parsed out of the current src/stage_test.asm so
the tileset never drifts) and replaces only stageMetatileRows with N rows of 10
IDs. The IDs vary by BOTH row and column and by the flat byte offset in a way
that any 8-bit truncation of the stage-map offset would corrupt:

    id(offset) = (offset * 7 + offset // 256 + row) % 16      offset = row*10 + col

so offset 0 and offset 256, or offset 250 and 256, choose different metatiles.
Rows 0 and N-1 are still all-M0 so the wrap seam stays visually continuous.

Usage:  python3 tools/make_stage_fixture.py N > src/generated/stage_test.asm
        (caller is responsible for setting .const STAGE_METATILE_ROWS = N and
         for restoring the originals afterwards, e.g. via git checkout)
"""
import re
import subprocess
import sys
from pathlib import Path

MPR = 10
DEF_COUNT = 16
ROOT = Path(__file__).resolve().parent.parent


def real_metatile_defs():
    # Take the 16-tile tileset from the live generated stage (its metatileDefs
    # block is the real, engine-consumed tileset). run_stage_fixture.sh backs up
    # and restores the generated files around the fixture run.
    text = (ROOT / 'src' / 'generated' / 'stage_test.asm').read_text(encoding='utf-8')
    block = text.split('metatileDefs:', 1)[1].split('METATILE_DEFS_END', 1)[0]
    rows = []
    for line in block.splitlines():
        line = line.split('//', 1)[0]
        nums = re.findall(r'\d+', line)
        if nums:
            rows.append([int(n) for n in nums])
    assert len(rows) == DEF_COUNT, f'expected {DEF_COUNT} metatile defs, got {len(rows)}'
    for r in rows:
        assert len(r) == 16, f'metatile def is not 16 bytes: {r}'
    return rows


def stage_row_ids(n_rows):
    for row in range(n_rows):
        ids = []
        for col in range(MPR):
            offset = row * MPR + col
            if row == 0 or row == n_rows - 1:
                ids.append(0)
            else:
                ids.append((offset * 7 + offset // 256 + row) % DEF_COUNT)
        yield row, ids


def main():
    n = int(sys.argv[1])
    defs = real_metatile_defs()
    out = []
    out.append('// ============================================================================')
    out.append(f'// DETERMINISTIC TEST FIXTURE - {n} metatile rows ({n*4} logical char rows,'
               f' {n*MPR}-byte map).')
    out.append('// Generated by tools/make_stage_fixture.py. Real 16 metatileDefs; synthetic')
    out.append('// stageMetatileRows: id = (offset*7 + offset//256 + row) % 16, seam rows all M0.')
    out.append('// Not for commit - restore src/generated/stage_test.asm afterwards.')
    out.append('// ============================================================================')
    out.append('')
    out.append('metatileDefs:')
    for i, d in enumerate(defs):
        out.append(f'    .byte {",".join(str(v) for v in d)}   // M{i}')
    out.append('METATILE_DEFS_END:')
    out.append('')
    out.append(f'// {n} rows x {MPR} metatile IDs.')
    out.append('stageMetatileRows:')
    for row, ids in stage_row_ids(n):
        body = ','.join(f'{v:2d}' for v in ids)
        out.append(f'    .byte {body}   // row {row}')
    out.append('STAGE_METATILE_ROWS_END:')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
