// ============================================================================
// Continuous four-colour bas-relief hull surface - visual proof stage.
// Auto-generated by scratchpad/relief.py; see docs/multicolour-terrain-worklog.md.
//
// The whole 320x800 stage is a constructed grey surface (Uridium-style depth
// from a restricted palette): the player is flying above the skin of one huge
// object. There is no empty black space - black only describes deep relief.
//
// Palette (global multicolour text mode; light source top-left):
//   00 black     = deep recesses, grooves, vents, strong shadow  (DEPTH)
//   01 grey (12) = dominant base plating / ordinary surface
//   10 lt grey   = raised faces and bevels
//   11 white     = highest edges / highlights
//
// Two tables (both future editor-generated):
//   metatileDefs      - METATILE_DEF_COUNT (16) definitions, 16 terrain char
//                        codes each (160..207), row-major 4x4.
//   stageMetatileRows - STAGE_METATILE_ROWS (25) rows of METATILES_PER_ROW (10)
//                        metatile IDs. Row 0 and row 24 are pure base plating
//                        so the grey surface continues unbroken across the
//                        logical-row 99 -> 0 wrap.
// Colour is NOT per cell: every playfield colour-RAM cell holds the single
// fixed TERRAIN_COLOUR_RAM value, so colour RAM never scrolls.
//
// The 16-metatile construction kit:
//   M0  PLATE   - plain grey base plating with a faint 32px plate grid
//   M1  R_FILL  - raised platform interior (light-grey top face, bosses)
//   M2  R_T     - raised platform north edge (white lit rim)
//   M3  R_B     - raised platform south edge (step-down + shadow line)
//   M4  R_L     - raised platform west edge (white lit rim)
//   M5  R_R     - raised platform east edge (step-down)
//   M6  R_TL    - raised platform NW outer corner
//   M7  R_TR    - raised platform NE outer corner
//   M8  R_BL    - raised platform SW outer corner
//   M9  R_BR    - raised platform SE outer corner
//   M10 CHAN_V  - vertical channel / groove (tiles top-bottom)
//   M11 CHAN_H  - full-width shallow channel (tiles left-right)
//   M12 RECESS  - inset panel: grey floor, shadow N/W, lit S/E (tiles into fields)
//   M13 GRILLE  - vent / grille bank on the base surface
//   M14 MACH    - machinery housing; the three turrets mount in its interior
//   M15 STEP    - quiet base plating + a small stepped surface detail / hazard
//
// M2..M9 combine into raised platforms of any size (the 4x4 grid is meant to be
// hard to see when scrolling). Turret world placements are in
// background_turrets.asm; each sits on a M14 MACH housing interior.
// ============================================================================

metatileDefs:
    .byte 160,160,160,162,  160,164,160,162,  160,160,165,162,  161,161,161,163   // M0 PLATE
    .byte 166,166,166,166,  166,168,166,166,  166,166,167,166,  166,166,166,166   // M1 R_FILL
    .byte 169,169,169,169,  166,166,166,166,  166,168,166,166,  166,166,166,166   // M2 R_T
    .byte 166,166,166,166,  166,168,166,166,  166,166,166,166,  170,170,170,170   // M3 R_B
    .byte 171,166,166,166,  171,166,167,166,  171,166,166,166,  171,166,166,166   // M4 R_L
    .byte 166,166,166,172,  166,167,166,172,  166,166,166,172,  166,166,166,172   // M5 R_R
    .byte 173,169,169,169,  171,166,166,166,  171,166,167,166,  171,166,166,166   // M6 R_TL
    .byte 169,169,169,174,  166,166,166,172,  166,167,166,172,  166,166,166,172   // M7 R_TR
    .byte 171,166,166,166,  171,166,167,166,  171,166,166,166,  175,170,170,170   // M8 R_BL
    .byte 166,166,166,172,  166,167,166,172,  166,166,166,172,  170,170,170,176   // M9 R_BR
    .byte 160,177,178,160,  160,177,178,160,  160,177,178,160,  160,177,178,160   // M10 CHAN_V
    .byte 160,160,160,160,  179,179,179,179,  180,180,180,180,  160,160,160,160   // M11 CHAN_H
    .byte 160,183,183,160,  185,187,187,186,  185,187,187,186,  160,184,184,160   // M12 RECESS
    .byte 160,188,188,160,  191,189,189,192,  191,189,189,192,  160,190,190,160   // M13 GRILLE
    .byte 173,169,169,174,  171,193,195,172,  171,194,196,172,  175,170,170,176   // M14 MACH
    .byte 160,160,197,162,  199,199,199,199,  160,200,160,162,  161,161,161,163   // M15 STEP
METATILE_DEFS_END:

// 10 metatile IDs per row (one screen width). Rows 0 and 24 are all-M0 so the
// grey base surface is continuous across the wrap; no structure terminates at
// row 23 and restarts wrongly at row 0.
stageMetatileRows:
    .byte  0, 0, 0, 0, 0, 0, 0, 0, 0, 0   // row  0  wrap seam - unbroken grey plating
    .byte  0, 0,15, 0, 0, 0, 0, 0,15, 0   // row  1
    .byte  0, 6, 2, 2, 2, 2, 2, 2, 7, 0   // row  2  A: broad raised platform across the width
    .byte  0, 4, 1, 1,14, 1, 1, 1, 5, 0   // row  3     turret 0 in the MACH housing (char rows 13-14, cols 17-18)
    .byte  0, 8, 3, 3, 3, 3, 3, 3, 9, 0   // row  4
    .byte  0, 0, 0,15, 0, 0, 0,15, 0, 0   // row  5
    .byte 10,10, 0,12,12, 0, 6, 2, 2, 7   // row  6  B: vertical channels W, inset-panel field, platform E
    .byte 10,10, 0,12,12, 0, 4,14, 1, 5   // row  7     turret 1 in the E-side MACH housing (char rows 29-30, cols 29-30)
    .byte 10,10, 0,12,12, 0, 4, 1, 1, 5   // row  8
    .byte 10,10, 0, 0, 0, 0, 8, 3, 3, 9   // row  9
    .byte  0, 0,15, 0, 0, 0, 0,15, 0, 0   // row 10
    .byte 11,11,11,11,11,11,11,11,11,11   // row 11  C: full-width shallow channel
    .byte  0, 0, 0, 0,13, 0, 0, 0, 0, 0   // row 12
    .byte  0, 0, 6, 2, 2, 2, 2, 7, 0, 0   // row 13  D: large 5-row structural massif
    .byte 15, 0, 4,14, 1, 1, 1, 5, 0,15   // row 14     turret 2 in the massif MACH housing (char rows 57-58, cols 13-14)
    .byte  0, 0, 4, 1,13, 1, 1, 5, 0, 0   // row 15
    .byte  0, 0, 4, 1, 1, 1, 1, 5, 0, 0   // row 16
    .byte  0, 0, 8, 3, 3, 3, 3, 9, 0, 0   // row 17
    .byte  0,15, 0, 0, 0, 0, 0, 0,15, 0   // row 18
    .byte 10,10, 0,13,13,13, 0,10,10, 0   // row 19  E: paired channels flanking a bank of vents
    .byte 10,10, 0,13,13,13, 0,10,10, 0   // row 20
    .byte  0, 0, 0, 0, 0, 0, 0, 0, 0, 0   // row 21
    .byte  0, 0, 6, 2, 2, 2, 2, 2, 7, 0   // row 22  F: one last broad platform, then fade to plating
    .byte  0, 0, 8, 3, 3, 3, 3, 3, 9, 0   // row 23
    .byte  0, 0, 0, 0, 0, 0, 0, 0, 0, 0   // row 24  wrap seam - unbroken grey plating
STAGE_METATILE_ROWS_END:
// Size guards, and the final BASIC-ROM overlap guard, live in main.asm right
// after this file's #import - KickAssembler resolves .if against the
// METATILE_*/STAGE_METATILE_ROWS constants more reliably there than inside
// an imported file. This file stays pure literal data.
